# -*- coding: utf-8 -*-
"""11_june_Text_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovJy2ZGn6LPQuyA2mIenW-Z6V4SqxN5L
"""

!pip install bertopic datamapplot
!pip install transformers==4.53.2 sentence-transformers==4.1.0
!pip install datasets==4.0.0 huggingface_hub==0.34.0
# bertopic==0.17.4 datamapplot==0.6.4

# Load data from huggingface
from datasets import load_dataset
dataset = load_dataset("maartengr/arxiv_nlp")["train"]

dataset[0]

dataset

# Extract metadata
abstracts = dataset["Abstracts"]
titles = dataset["Titles"]

abstracts

len(abstracts)

titles

abstracts[0]

titles[0]

# A COMMON PIPLINE FOR TEXT CLUSTERING

# 1. Embedding Documents

from sentence_transformers import SentenceTransformer

# Create an embedding for each abstract
embedding_model = SentenceTransformer('thenlper/gte-small')
embeddings = embedding_model.encode(list(abstracts), show_progress_bar=True)

embeddings

embeddings.shape

# 2. Reducing the Dimensionality of Embeddings

from umap import UMAP

# We reduce the input embeddings from 384 dimenions to 5 dimenions
umap_model = UMAP(
    n_components=5, min_dist=0.0, metric='cosine', random_state=42
)
reduced_embeddings = umap_model.fit_transform(embeddings)

reduced_embeddings.shape

# 3. Cluster the Reduced Embeddings

from hdbscan import HDBSCAN

# We fit the model and extract the clusters
hdbscan_model = HDBSCAN(
    min_cluster_size=50, metric='euclidean', cluster_selection_method='eom'
).fit(reduced_embeddings)
clusters = hdbscan_model.labels_

clusters

set(clusters)

len(set(clusters))

# Inspecting the Clusters

# Manually inspect the first three documents in cluster 0

import numpy as np
# Print first three documents in cluster 0
cluster = 0
for index in np.where(clusters==cluster)[0][:3]:
    print(abstracts[int(index)][:300] + "... \n")

import numpy as np

# Print first three documents in cluster 10
cluster = 10
for index in np.where(clusters==cluster)[0][:3]:
    print(abstracts[int(index)][:300] + "... \n")

import numpy as np

# Print first three documents in cluster 5
cluster = 5
for index in np.where(clusters==cluster)[0][:3]:
    print(abstracts[int(index)][:300] + "... \n")

import pandas as pd

# Reduce 384-dimensional embeddings to 2 dimensions for easier visualization
reduced_embeddings = UMAP(
    n_components=2, min_dist=0.0, metric='cosine', random_state=42
).fit_transform(embeddings)

reduced_embeddings.shape

reduced_embeddings

# Create dataframe
df = pd.DataFrame(reduced_embeddings, columns=["x", "y"])
df["title"] = titles
df["cluster"] = [str(c) for c in clusters]

df

# Select outliers and non-outliers (clusters)
clusters_df = df.loc[df.cluster != "-1", :]
outliers_df = df.loc[df.cluster == "-1", :]

clusters_df

outliers_df

import matplotlib.pyplot as plt

# Plot outliers and non-outliers seperately
plt.scatter(outliers_df.x, outliers_df.y, alpha=0.05, s=2, c="grey")
plt.scatter(
    clusters_df.x, clusters_df.y, c=clusters_df.cluster.astype(int),
    alpha=0.6, s=2, cmap='tab20b'
)
plt.axis('off')
# plt.savefig("matplotlib.png", dpi=300)  # Uncomment to save the graph as a .png

# BERTopic: A Modular Topic Modeling Framework

from bertopic import BERTopic

# Train our model with our previously defined models
topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    verbose=True
).fit(abstracts, embeddings)

topic_model.get_topic_info()

topic_model.get_topic(0)

topic_model.get_topic(1)

topic_model.find_topics("topic modeling")

topic_model.get_topic(24)

topic_model.find_topics("biomedical")

topic_model.get_topic(1)

topic_model.get_topic(48)

topic_model.get_topic(83)

topic_model.topics_[titles.index('BERTopic: Neural topic modeling with a class-based TF-IDF procedure')]

topic_model.get_topic(24)

z# Visualize topics and documents
fig = topic_model.visualize_documents(
    list(titles),
    reduced_embeddings=reduced_embeddings,
    width=1200,
    hide_annotations=True
)

# Update fonts of legend for easier visualization
fig.update_layout(font=dict(size=16))

# Visualize barchart with ranked keywords
topic_model.visualize_barchart()

# Visualize relationships between topics
topic_model.visualize_heatmap(n_clusters=30)

# Visualize the potential hierarchical structure of topics
topic_model.visualize_hierarchy()

