# -*- coding: utf-8 -*-
"""19_may_Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-jCjC6iqs0CLvXkEr8zJ6Wi8VusL7Oe
"""

!pip install gensim

import gensim.downloader as api

# Download embeddings (66MB, glove, trained on wikipedia, vector size: 50)
# Other options include "word2vec-google-news-300"
# More options at https://github.com/RaRe-Technologies/gensim-data
model = api.load("glove-wiki-gigaword-50")

model.get_vector('apple')

model.get_vector('apple').shape

model.get_vector('king')

model.most_similar([model['king']], topn=3)

model.most_similar([model['rich']], topn=3)

#  Recommending songs by embeddings

import pandas as pd
from urllib import request

# Get the playlist dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

lines

len(lines)

lines[0]

lines[999]

lines[200]

# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

playlists[0]

playlists[2]

# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs_file

songs = [s.rstrip().split('\t') for s in songs_file]

songs

songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df

songs_df=songs_df.set_index('id')

songs_df.iloc[90]

print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

from gensim.models import Word2Vec

# Train our Word2Vec model
model = Word2Vec(
    playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4
)#  window: The context distance. The model looks at 20 songs before and 20 songs after a target song in a playlist to figure out how they relate.
#negative = 50: Negative sampling(compare with 50 words)
#workers = 4(4 processor use krta hai)

song_id = 2172

# Ask the model for songs similar to song #2172
model.wv.most_similar(positive=str(song_id))

songs_df.iloc[3167]

import numpy as np

def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations
print_recommendations(2172)

# Extract recommendations
print_recommendations(1922)

# Extract recommendations
print_recommendations(2000)

