# -*- coding: utf-8 -*-
"""Copy of 4_june_simple_gpt_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8SCJv1hUiDyjMgIlCztbEPXZVhcWtHL
"""

!pip install transformers[sentencepiece]

from transformers import pipeline

generator=pipeline("text-generation")

generator("In this course,we will teach you how to")

generator("In this course, we will teach you how to")[0]

generator("In this course, we will teach you how to")[0]['generated_text']

# # Using any model from hub in pipeline

generator = pipeline("text-generation",model = 'distilgpt2') # quantized model(model ko compress krta hey)

generator("In this course, we will teach you how to")[0]

generator("In this course, we will teach you how to")[0]['generated_text']

generator("In this course, we will teach you how to",
          max_length = 30,
          num_return_sequences = 2)# 2 output diffrent.

generator("In this course, we will teach you how to",
          max_length = 30,
          num_return_sequences = 2)[1]['generated_text']

generator("In this course, we will teach you how to",
          max_length = 30,
          num_return_sequences = 2)[0]['generated_text']

from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
model = AutoModelForCausalLM.from_pretrained("distilgpt2")

text = "The Shawshank"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

input

# do_sample --- if false same output everytime
# do_sample----if true then output is differentied
# Run the model
output = model.generate(input, max_length=5, do_sample=False)
output

output[0]

# Print the output
print('\n',tokenizer.decode(output[0]))

tokenizer.convert_ids_to_tokens(input[0])

# This is the embedding matrix of the model
model.transformer.wte # Dimensions are: (Number of tokens in vocabulary, dimension of model)

# Get the embedding vector of token # 464 ('The')
import torch
model.transformer.wte(torch.tensor(464))

text = "The chicken didn't cross the road because it was"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=50, do_sample=True)

# Print the output
print('\n',tokenizer.decode(output[0]))

text = "The chicken didn't cross the road because it was"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=50, do_sample=True)

# Print the output
print('\n',tokenizer.decode(output[0]))

